### ISSUE TITLE
上传过程报错

### ISSUE THREAD

**Issue by wh469012917** [qtrade-fe/webpack-qcloud-cos-plugin#2]
![QQ截图20200217144931](https://user-images.githubusercontent.com/10496478/74630110-ccba6a00-5194-11ea-9d03-7a07f120e40c.png)
方便协助排查一下吗？

**Comment by GuiGu0101** [comment]
这个看堆栈信息，是webpack-theme-color-replacer部分报的错，是否使用了Ant Design？
请联系Ant Design看看

**Comment by wh469012917** [comment]
@GuiGu0101 对使用了 ant design pro，但是假如没有cos webpack插件的话就一切正常，build也可以正常打包出来，就加了你们这个之后就报错了
