### ISSUE TITLE
1.1.2版本 设置useVersion: true不生效，没有读取package.json中的version

### ISSUE THREAD

**Issue by slacrey** [qtrade-fe/webpack-qcloud-cos-plugin#4]
代码中的判断是 this.config.version = this.config.version || getNpmName();
this.config.version的值是“”，所以上面表达式不成立

**Comment by GuiGu0101** [comment]
在` this.config.version = ''`的情况下，上述表达式时成立的，会执行this.npmProjectVersion();

**Comment by GuiGu0101** [comment]
> 代码中的判断是 this.config.version = this.config.version || getNpmName();
> this.config.version的值是“”，所以上面表达式不成立

在js中
`!!test`在test值为`undefined` \ `null` \ `''`情况下都将返回`false`
`!test`在test值为`undefined` \ `null` \ `''`情况下都将返回`true`

所以请检查是否配置有误，
